name: deployment in Vercel

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    avoid_reduncy:
        runs-on: ubuntu-22.04
        steps:
            - name: Cancel redundant builds
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                access_token: ${{ github.token }}
                
    lint:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Install Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '22'
            
            - name: Install Dependencies
              run: npm ci --no-audit
            
            - name: Lint Analysis CI
              run: echo "Should run npm run lint"
        
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Install Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '22'

            - name: Install Dependencies
              run: npm ci --no-audit
            
            - name: Build Project
              run: npm run build

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist

    test:
        needs: [lint, build]
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Install Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '22'
            
            - name: Install Dependencies
              run: npm ci --no-audit

            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: dist
                path: dist

            - name: Run Tests
              run: echo "No tests to run yet"

    e2e: 
        needs: [lint, build]
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
              
            - name: Install Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '22'

            - name: Install Dependencies
              run: npm ci --no-audit

            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: dist
                path: dist

            - name: Run E2E Tests
              run: echo "No E2E tests to run yet"     

    
    deploy:
        needs: [test, e2e]
        runs-on: ubuntu-22.04
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'patomomo-dev/fluffy-deals-hub'
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Deploy to Vercel
              uses: nexterias/actions-vercel@v1
              with:
                token: ${{ secrets.VERCEL_TOKEN }}
                org-id: ${{ secrets.VERCEL_ORG_ID }}
                project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                production: ${{ github.ref == 'refs/heads/main' }}
                prebuilt: true
            